## Analyzing simulation output

First, we create a data object, which we point to the top-level output directory `CrNiP`. The object recursively finds all files in `CrNiP` and provides access to the simulation results from within Python.

In [1]:
from mammos_spindynamics import uppasd

In [2]:
data = uppasd.read("my-first-simulation")
data

MammosUppasdData('my-first-simulation')

In [3]:
repr(data)

"MammosUppasdData('my-first-simulation')"

In [4]:
data.runs

[{'id': 'run-0',
  'UppASD version': 'v6.0.2',
  'elapsed_time': '01:00:00',
  'end_time': '2025-11-26T13:00:00',
  'mammos_spindynamics_version': '0.2.2',
  'mode': 'run',
  'start_time': '2025-11-26T12:00:00',
  'T': 10}]

In [5]:
data.info

,id,UppASD version,elapsed_time,end_time,mammos_spindynamics_version,mode,start_time,T
0,run-0,v6.0.2,01:00:00,2025-11-26T13:00:00,0.2.2,run,2025-11-26T12:00:00,10

In [6]:
uppasd.MammosUppasdData("my-first-simulation")

MammosUppasdData('my-first-simulation')

We only have one set of outputs in this example. We can acces it as follows:

In [7]:
run_data = data[0]
run_data

RunData('my-first-simulation/run-0')

In [8]:
uppasd.RunData("my-first-simulation/run-0")

RunData('my-first-simulation/run-0')

In [9]:
uppasd.read("my-first-simulation/run-0")

RunData('my-first-simulation/run-0')

The object allows us to access the array-like simulation output and the temperatures:

In [10]:
run_data.T

10.0

In [11]:
run_data.Ms

Entity(ontology_label='SpontaneousMagnetization', value=np.float64(2642.0947009651604), unit='A / m')

In [12]:
run_data.metadata

{'UppASD version': 'v6.0.2',
 'elapsed_time': '01:00:00',
 'end_time': '2025-11-26T13:00:00',
 'mammos_spindynamics_version': '0.2.2',
 'mode': 'run',
 'start_time': '2025-11-26T12:00:00'}

In [13]:
run_data.parameters

{'T': 10}

In [14]:
run_data.restart_file

PosixPath('my-first-simulation/run-0/restart.bccFe100.out')

In [15]:
run_data.describe(
    include_elapsed_time=True,
    include_index=False,
    include_options=True,
    include_comment=True,
)

In [17]:
# run_10K.inpsd_inp.read_text()
run_data.input_dictionary

{'simid': 'bccFe100',
 'ncell': array([25., 25., 25.]),
 'BC': ['P', 'P', 'P'],
 'cell': array([[ 5.05758866, -2.92000017,  0.        ],
        [ 0.        ,  5.84000034,  0.        ],
        [ 0.        ,  0.        ,  3.51400021]]),
 'posfile': 'D',
 'posfiletype': 'D',
 'momfile': './momfile',
 'exchange': './jASD2',
 'do_ralloy': 0,
 'Mensemble': 1,
 'tseed': 4499,
 'maptype': 3,
 'SDEalgh': 1,
 'Initmag': 3,
 'ip_mode': 'M',
 'ip_mcanneal': 1,
 'temp': 10.0,
 'mcNstep': 700,
 'damping': 0.1,
 'timestep': 1e-16,
 'do_avrg': 'Y',
 'do_cumu': 'Y',
 'cumu_step': 50,
 'cumu_buff': 10,
 'do_tottraj': 'Y',
 'tottraj_step': 1000,
 'plotenergy': 1,
 'do_sc': 'C',
 'do_ams': 'Y',
 'do_magdos': 'Y',
 'magdos_freq': 200,
 'magdos_sigma': 30,
 'qpoints': 'C',
 'do_stiffness': 'Y',
 'eta_max': 12,
 'eta_min': 6,
 'alat': 1e-10}